### ISSUE TITLE
can we understand this method as a generalization of factorization machine? 

### ISSUE THREAD

**Issue by shalijiang** [Justin1904/Low-rank-Multimodal-Fusion#12]
Very interesting work! A quick question, can we understand this method as a generalization of factorization machine (https://cseweb.ucsd.edu/classes/fa17/cse291-b/reading/Rendle2010FM.pdf)? it appears to me the high level idea is similar, but generalized to high-dim tensor. Let me know if I misunderstood :)

**Comment by Justin1904** [comment]
That's an interesting observation and education for myself... Yes, after a quick glance I feel like the idea is quite similar, the FM paper also has the d-way case which is about higher dimensional cases. The main difference here I guess is that in our paper we want the LMF layer to output a vector instead of a scalar and use it as an intermediate hidden layer instead of the final prediction layer, so the factorization is a little different (not a standard PARAFAC where you factorize tensors into vector tuples, instead we factorize into matrix tuples where the extra dimension is the output hidden dimension). But yes I feel like the intuition and the approach is pretty similar. I'd say compare to the original FM the interesting bits here is we extend it to become a layer with arbitrary output size hence making it generally composable into neural nets.
