### ISSUE TITLE
A question about formula (6)

### ISSUE THREAD

**Issue by oyss1996** [Justin1904/Low-rank-Multimodal-Fusion#17]
Why can the order of summation and Hadamard product be exchanged in the last step of formula (6)?
I tried the simplest case (when w is a vector, r=2, m=2) and found that exchange the order will bring extra interleaved items.

**Comment by Justin1904** [comment]
Thank you for the question! This is because I made an error in equation (6), please use equation (8) as the reference for implementation (actually I started with equation 8 and wrote the code, and later during writing the paper I wanted to provide some more intuition hence came equation 6, but sadly I made an error in that equation). For more details you can refer to this discussion here #14
