### ISSUE TITLE
 How many times did you use the 8895952 combination? How much time does each data set need to train?

### ISSUE THREAD

**Issue by Paidalin** [Justin1904/Low-rank-Multimodal-Fusion#5]
Recently I want to use your LMF to fuse my three modes for training. I want to know how long does it take for the whole process?

**Comment by Justin1904** [comment]
I guess that depends on the size of your data as well as your computation power. The best way to figure that out is to take a small subset of your data and see how long does it take to process them.

As for training, there's also the factor of early stopping. Since there is some randomness to it, it is very hard to tell how long one training run would take. I roughly remembered that training the model on MOSI with the provide features takes about 10-15min with patience~10 on a 1080Ti. YMMV.

**Comment by Paidalin** [comment]
Do you mean that training for a set of parameters takes 10-15 minutes?But there are too many parameter combinations in the whole process.I only got the result of about 200 parameter combinations in one night.So how do I know the accuracy and parameters of the optimal model?

**Comment by Justin1904** [comment]
The search for optimal hyperparameter is in fact an open question to the best of my knowledge. What we are doing here is called grid search, which is basically randomly search on a grid formed by sets of possible values of each hyperparameter. The usual practice is to let the grid search run for as long as you can afford and pick the best result/model you've got. Searching for "the" optimal hyperparameter setting is a lost cause since the space of hyperparameters is continuous. Note that the combinations we have here is merely a discrete and countable subset of that space and is no way exhaustive or representative of the entire space. We are only trying to "do our best" when searching for the best hyperparameter, and take whatever best result we've got in a realistic amount of time.

On Mar 13, 2019, at 2:18 AM, Paidalin <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you mean that training for a set of parameters takes 10-15 minutes?But there are too many parameter combinations in the whole process.I only got the result of about 200 parameter combinations in one night.So how do I know the accuracy and parameters of the optimal model?

**Comment by Paidalin** [comment]
ok，thank you for your answer
