### ISSUE TITLE
Epoch 0 complete! Average Training loss: nan

### ISSUE THREAD

**Issue by xiaoiker** [Justin1904/Low-rank-Multimodal-Fusion#8]
Hello, when I run the train_mosi.py script, I get NAN from the very beginning. Is that normal?

Best!

**Comment by Justin1904** [comment]
That is probably because there are inf/nan values in the data (as I recall there is some in acoustic features). I thought I have removed them during processing but apparently, I didn't. What you could do is to remove those NaN and Inf values.

**Comment by xiaoiker** [comment]
Do you means than I remove all the data with NaN and Inf values?
BTW, I get another question. Can you tell me how can I get the tool you listed in the footnote? Once I search on goo.gl/1rh1JN, it would navigated to https://imotions.com/.  

Thanks very much!

**Comment by Justin1904** [comment]
For the first question, yes. For the second question, FACET is a proprietary software and that's why you are redirected to their product page instead of a paper or a open source software repo. If you are looking for open source alternatives for FACET facial recognition toolkit, I recommend [OpenFace](https://github.com/TadasBaltrusaitis/OpenFace), with which we later experimented with and showed better performance.

**Comment by xiaoiker** [comment]
Great, I really appreciate your kindness reply.
